---
title: "creating graphs in R with ggplot2"
author: "Andre M Chagas"
date: "16/07/2020"
output: html_document
---
# Plots with ggplot2

We are going to make plots in R and it's going to be amazing.

"We use the following data from the Santa Barbara Coastal Term Ecological Research and National  Oceanic and Atmospheric Administration in our analyses"

```{r attach-libraries}
library(tidyverse)

library(readxl)

library(here)
```


```{r open-csv}

ca_np<-read.csv(here("data","ca_np.csv"))

head(ca_np)
summary(ca_np)


```


```{r open-excel}

ci_np <- read_excel(here("data", "ci_np.xlsx"))


```


```{r ggplot2}

ggplot(data = ci_np, aes(x = year, y = visitors)) +  geom_line()


gg_base<-ggplot(data = ci_np, aes(x = year, y = visitors)) 
#this above is indeed quite nice. you store in a variable just the data, 
#x and y information and then "map it" to a plot type (see below)

gg_base+geom_point()

gg_base+geom_col()


gg_base +
  geom_line(
    color = "purple",
    linetype = "dashed"
  )

```

``` {r conditional-plot}

gg_base + 
  geom_point(
    aes(size = visitors,
        color = visitors),
    alpha = 0.5
  )

gg_base + 
  geom_col(aes(fill = visitors))


gg_base +
  geom_point(
    aes(size = visitors,
        color = visitors),
    alpha = 0.5
  ) +
  theme_minimal()

gg_base +
  geom_line(linetype = "dotted") +
  theme_bw() +
  labs(
    x = "Year",
    y = "Annual park visitors",
    title = "Channel Islands NP Visitation",
    subtitle = "(1963 - 2016)"
    #legend = "test" 
)



gg_base +
  geom_line(color = "purple") +
  geom_point(color = "orange",
             aes(size = year),
             alpha = 0.5)

```
``` {r multi-series}
#adding 'group' allows to plot multiple series. in this specific case park_name is the name of a column
head(ca_np)
ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name)) +
  geom_line()


gg_np <- ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name))


gg_np +
  geom_line(show.legend = FALSE) +
  theme_light() + 
  labs(x = "year", y = "annual visitors") +
  facet_wrap(~ park_name)


ggsave(here("figures", "np_graph.jpg"), dpi = 180, width = 8, height = 7)

```
